PROJECT-3
danek0100/backend_course pull request #10
Opened 2023-11-19 20:50 UTC by danek0100

2023-12-02 19:18 UTC, kkmikhaylova requested changes

2023-12-02 19:18 UTC, kkmikhaylova commented on src/main/java/edu/project3/ArgumentsAnalyzer.java
> +
Лучше catch не оставлять пустым, хотя бы нужно залогировать исключение. Ниже аналогично

2023-12-02 19:18 UTC, kkmikhaylova commented on src/main/java/edu/project3/ArgumentsAnalyzer.java
> +                parseState = AVAILABLE_ARGS.indexOf(arg);
Аргументы не обязательно будут в том же порядке

2023-12-02 19:18 UTC, kkmikhaylova commented on src/main/java/edu/project3/ArgumentsAnalyzer.java
> +        int parseState = -1;
Логика с parseState сложновата для понимания, её бы упростить

2023-12-02 19:18 UTC, kkmikhaylova commented on src/main/java/edu/project3/LogAnalyzer.java
> +        //TODO максимальное число запросов в минуту
Нужно доделать

2023-12-02 19:18 UTC, kkmikhaylova commented on src/main/java/edu/project3/LogAnalyzer.java
> +                lines.forEach(line -> updateStatistics(parseLogEntry(line)));
Обновление статистики - неочевидный сайд эффект вызова функции `parseLogsFromURL`, от сайд эффектов лучше избавляться. Судя по названию функции, она должна вернуть список элементов `LogRecord`, давай так и сделаем. А статистику будем анализировать уровнем выше, после вызова `parseLogsFromURL`.

2023-12-03 10:14 UTC, danek0100 commented on src/main/java/edu/project3/ArgumentsAnalyzer.java
> +                parseState = AVAILABLE_ARGS.indexOf(arg);
Порядок аргументов не влияет на работу программы

2023-12-04 18:31 UTC, kkmikhaylova approved these changes
👍

2023-12-09 11:19 UTC, merged