HW-2
danek0100/backend_course pull request #3
Opened 2023-10-21 10:54 UTC by danek0100

2023-10-22 21:05 UTC, kkmikhaylova requested changes
Оставила пару мелких комментов по заданию 2, в остальном все ок 👍

2023-10-22 21:05 UTC, kkmikhaylova commented on src/test/java/edu/hw2/Task2Test.java
> +        assertThat(rect.area()).isEqualTo(rect instanceof Task2.Square ? 100 : 200.0);
Тест из задания должен проходить как есть, без дополнительных доработок, instanceof нужно убрать

2023-10-22 21:05 UTC, kkmikhaylova commented on src/main/java/edu/hw2/Task2.java
> +        public Square setWidth(int side) {
Из-за переопределения этих методов (`setWidth`/`setHeight`), попал обратно в ловушку парадокса). Поведение этих методов для класса `Square` должно быть аналогично `Rectangle`, не нужно их переопределять

2023-10-23 16:55 UTC, danek0100 commented on src/test/java/edu/hw2/Task2Test.java
> +        assertThat(rect.area()).isEqualTo(rect instanceof Task2.Square ? 100 : 200.0);
Вернул тест к первоначальному виду

2023-10-23 16:56 UTC, danek0100 commented on src/main/java/edu/hw2/Task2.java
> +        public Square setWidth(int side) {
Убрал переопределение методов - тест прошёл без instaceof :)

2023-10-23 22:50 UTC, kkmikhaylova approved these changes

2023-10-28 06:34 UTC, merged